# Generated by Django 4.2.6 on 2023-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ccode', models.CharField(max_length=100)),
            ],
        ),
    ]
